# -*- coding: utf-8 -*-
"""RahulTask4changes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PCLeQ4MCq5SZmXJ-fXt6uqtQSwEtSNXj
"""

pip install streamlit

pip install google-generativeai

import streamlit as st
import google.generativeai as ai

# Configure API key securely (Avoid hardcoding sensitive data)
ai.configure(api_key="AIzaSyCHGvCV_UsrQLx8EZrb58IQ9qqQEyRNcYI")

# Define system prompt for the AI model
sys_prompt = """You are a helpful AI Tutor for Data Science.
                Students will ask you doubts related to various topics in data science.
                You are expected to reply in as much detail as possible.
                Make sure to take examples while explaining a concept.
                In case if a student ask any question outside the data science scope,
                politely decline and tell them to ask the question from data science domain only.
                Always include a helpful statement at the end saying that
                'In case if your query is not resolved, feel free to click on this link:
                innomatics.in to get in touch with our mentor in a 1:1 zoom call'"""

# Initialize the generative AI model
gemini_model = ai.GenerativeModel(model_name="models/gemini-1.5-pro", system_instruction=sys_prompt)

# Streamlit UI
st.title("Data Science/AI TUTOR")

# Get user input
user_input = st.text_input("Ask a question related to Data Science:")

if user_input:
    # Generate response
    try:
        response = gemini_model.generate(prompt=user_input)
        st.write(response.text)
    except Exception as e:
        st.error(f"An error occurred: {e}")